name: CI-CD deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: List repository contents
        run: ls -R

      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: ./WebApplication1test_ci_cd/bin/Release/net8.0  # Update this path based on your project structure

      - name: Build app
        run: dotnet build -c Release --no-restore

      - name: List files after archive
        run: ls -liaR ./WebApplication1test_ci_cd/bin/Release/net8.0  # Verify the path is correct


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts1
        uses: actions/download-artifact@v3
        with:
          name: app-artifact

      - name: List downloaded files
        run: ls -R /home/runner/work/CI-CD-YT/CI-CD-YT

      - name: Create artifacts directory
        run: mkdir -p ./WebApplication1test_ci_cd/bin/Release/net8.0  # Update this path based on your project structure

      - name: List files after archiveBC
        run: ls -R ./WebApplication1test_ci_cd/bin/Release/net8.0  # Verify the path is correct

      - name: Check directory permissions
        run: ls -la ./WebApplication1test_ci_cd/bin/Release/net8.0  # Verify the path is correct

      - name: Create ZIP
        run: zip -r app-artifact.zip /home/runner/work/CI-CD-YT/CI-CD-YT  # Verify the path is correct

      - name: Upload ZIP
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact.zip
          path: app-artifact.zip
