name: CI-CD deplyment

on:
  push: 
    branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out2
              uses: actions/checkout@v4

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3.2.0
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies 
              run: dotnet restore

            - name: Archive artifacts
              uses: actions/upload-artifact@v2
              with:
                name: app-artifact
                path: ./bin/Release/net8.0  # Zmeň cestu na odpovedajúce umiestnenie výstupných súborov

    deploy:
                    needs: build
                    runs-on: ubuntu-latest
                    steps:
                      - name: Download artifacts
                        uses: actions/download-artifact@v2
                        with:
                          name: app-artifact
                
                      - name: Create ZIP
                        run: zip -r app-artifact.zip ./netcoreapp3.1
                
                      - name: Upload ZIP
                        uses: actions/upload-artifact@v2
                        with:
                          name: zipped-artifact.zip
                          path: app-artifact.zip