name: CI-CD deplyment

on:
    push: 
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v3.2.0
              with:
                dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build app
              run: dotnet build -c Release --norestore

              


